# Generated by Django 3.2.12 on 2022-03-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co2_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CO2DataFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('time', models.TimeField()),
                ('frequency', models.IntegerField()),
            ],
        ),
    ]
